#pragma once
#include <cstddef>
#include <cstdint>
#include <omp.h>
#include <random>
#include <vector>

#include <fstream>
#include <ios>
#include <iostream>
#include <nlohmann/json.hpp>
#include <stdexcept>

class Lattice {
private:
  /* Variable: Lattice.rows; (private)
   * int rows; number of rows in lattice
   */
  int rows;

  /* Variable: Lattice.cols; (private)
   * int cols; number of columns in lattice
   */
  int cols;

  /* Variable: Lattice.temp; (private)
   * double temp; temperature of system
   */
  double temp;

  /* Variable: Lattice.N; (private)
   * size_t N; total number of sites in lattice
   */
  size_t N;

  /* Variable: Lattice.rows; (private)
   * int ext_H; external magnetic field acting on lattice
   */
  double ext_H = 5.0;

  /* Variable: Lattice.rows (private)
   * std::vector<int8_t> spins; flattened array holding the spin state
   * of each site (should ALWAYS be +/- 1)
   */
  std::vector<int8_t> spins;

  /* Method: Lattice::load_binary_map(const std::string &path,
   * std::vector<double> &target, size_t expected_size); (private)
   * Returns: (void); Interprets binary maps generated by grid_helper.py
   */
  void load_binary_map(const std::string &path, std::vector<double> &target,
                       size_t expected_size) {
    std::ifstream file(path, std::ios::binary);
    if (!file) {
      throw std::runtime_error("Could not find/open map at:" + path);
    }

    target.resize(expected_size);
    file.read(reinterpret_cast<char *>(target.data()),
              expected_size * sizeof(double));
  }

  // DOESNT WORK!!
  void populate_lattice() {
#pragma omp parallel
    {
      std::uniform_int_distribution<int> spin_dist(0, 1);

      thread_local std::mt19937 gen(std::random_device{}() +
                                    omp_get_thread_num());

#pragma omp for
      for (int i = 0; i < static_cast<int>(N); ++i) {
        spins[i] = spin_dist(gen) ? 1 : -1;
      }
    }
  }

public:
  /* Constructor: Lattice::Lattice(const nlohmann::json &j); (public)
   * Returns: (void); reads json file j and attempts to pull number of rows,
   * columns, and temperature from config.  Pulls the spin grid and couplings
   * from the binary maps generated by grid_helper.py.
   *
   * Updates:
   *    int                 rows;       (private)
   *    int                 cols;       (private)
   *    double              temp;       (private)
   *    size_t              N;          (private)
   *    std::vector<double> field;      (public)
   *    std::vector<double> x_coupling; (public)
   *    std::vector<double> y_coupling; (public)
   *
   * Note: Paths should be automatically generated by grid_helper.py;
   *  if having issues, always make sure to generate config and binaries
   *  from "$[PROJECT ROOT]/scripts/grid_helper.py"
   */
  Lattice(const nlohmann::json &j, bool random_initial = true) {
    if (!j.contains("rows") || !j.contains("cols") || !j.contains("T")) {
      throw std::runtime_error("json config missing required keys (one or more "
                               "of: 'rows', 'cols', 'T'.)");
    }
    rows = j["rows"];
    cols = j["cols"];
    temp = j["T"];
    N = static_cast<size_t>(rows * cols);

    spins.resize(N);
    if (random_initial) {
      populate_lattice();
    } else {
      throw std::runtime_error("!!Error!! bool 'random_initial' returned "
                               "FALSE: Logic not implemented yet.\n");
    }

    load_binary_map(j["field_map"], field, N);
    load_binary_map(j["h_coupling_map"], x_coupling, N);
    load_binary_map(j["v_coupling_map"], y_coupling, N);
  }

  /* Accessor: Lattice::get_index(int x, int y); (public)
   * Returns: (size_t);  Handles indexing for internal methods.  Allows for
   * flattened binary representations of (Lattice) objs ==> improving speed in
   * computation
   */
  inline size_t get_index(int x, int y) const {
    auto wrapX = [this](int val) { return (val % rows + rows) % rows; };
    auto wrapY = [this](int val) { return (val % cols + cols) % cols; };
    return wrapX(x) * y + wrapY(y);
  };

  /* Accessor: Lattice::get_spin(size_t idx); (public)
   * Returns: (int8_t); returns current spin state at idx.  Indexing handled by
   * Lattice::get_index.
   */
  int8_t get_spin(size_t idx) const { return spins[idx]; };

  /* Method: Lattice::flip_spin(size_t idx); (public)
   * Returns: (void);  Flips spin at idx. Indexing handled by
   * Lattice::get_index.
   */
  void flip_spin(size_t idx) {
    spins[idx] *= -1;
    return;
  };

  /* Accessor: Lattice.size(); (public)
   * Returns: (std::vector<int>); returns vector holding {rows, cols}.
   */
  std::vector<int> get_size() { return {rows, cols}; };

  /* Accessor: Lattice.total_sites(); (public)
   * Returns: (int); returns number of sites (rows * cols).
   */
  int total_sites() const { return N; };

  /* Accessor: Lattice.get_temp(); (public)
   * Returns: (double); returns the user configured temperature of system.
   */
  double get_temp() const { return temp; };

  /* Accessor: Lattice.get_ext_H(); (public)
   * Returns: (double); returns user configured external
   *    magnetic field of system.
   */
  double get_ext_H() const { return ext_H; };

  /* Accessor: Lattice.spin_pointer(); (public)
   * Returns: (std::vector<int8_t>*); returns pointer to spin state array.
   */
  std::vector<int8_t> *spin_pointer() { return &spins; };

  /* Variable: Lattice.field (public)
   * std::vector<double> field; flattened array of internal magnetic
   *    field values at sites.
   */
  std::vector<double> field;

  /* Variable: Lattice.x_coupling (public)
   * std::vector<double> x_coupling; flattened array holding the
   *    horizontal couplings between sites in the lattice.
   */
  std::vector<double> x_coupling;

  /* Variable: Lattice.y_coupling (public)
   * std::vector<double> y_coupling; flattened array holding the
   *    vertical couplings between sites in the lattice.
   */
  std::vector<double> y_coupling;
};
